#!/bin/bash

PID_FILE=${PID_FILE-/var/run/mysqld/mysqld.pid}
DELAY=${DELAY-3}

alias wait_pid='watch_pid 0'

function watch_pid {
    # if $1 == 1 it will watch a file until it is gone
    # otherwise it will wait for the file until it is present
    WATCH=${1-1}
    if [ -f ${PID_FILE} ];then
        if [ "X${WATCH}" == "X1" ];then
            sleep ${DELAY}
            watch_pid ${WATCH}
        else
            return 0
        fi
    else
        if [ ${WATCH} -eq 1 ];then 
            return 1
        else
            sleep ${DELAY}
            watch_pid ${WATCH}
        fi
    fi
}
